package org.stg.core;

import java.util.ArrayList;
import java.util.List;

public class CountryUtil {

    List<String> countryNames = new ArrayList<String>();

    public CountryUtil() {
        countryNames.add("Afghanistan");
        countryNames.add("Albania");
        countryNames.add("Algeria");
        countryNames.add("Andorra");
        countryNames.add("Angola");
        countryNames.add("Antigua and Barbuda");
        countryNames.add("Argentina");
        countryNames.add("Armenia");
        countryNames.add("Australia");
        countryNames.add("Austria");
        countryNames.add("Azerbaijan");
        countryNames.add("Bahamas");
        countryNames.add("Bahrain");
        countryNames.add("Bangladesh");
        countryNames.add("Barbados");
        countryNames.add("Belarus");
        countryNames.add("Belgium");
        countryNames.add("Belize");
        countryNames.add("Benin");
        countryNames.add("Bhutan");
        countryNames.add("Bolivia, Plurinational State of");
        countryNames.add("Bosnia and Herzegovina");
        countryNames.add("Botswana");
        countryNames.add("Brazil");
        countryNames.add("Brunei Darussalam");
        countryNames.add("Bulgaria");
        countryNames.add("Burkina Faso");
        countryNames.add("Burundi");
        countryNames.add("Cambodia");
        countryNames.add("Cameroon");
        countryNames.add("Canada");
        countryNames.add("Cabo Verde");
        countryNames.add("Central African Republic");
        countryNames.add("Chad");
        countryNames.add("Chile");
        countryNames.add("China");
        countryNames.add("Colombia");
        countryNames.add("Comoros");
        countryNames.add("Congo");
        countryNames.add("Congo, the Democratic Republic of the");
        countryNames.add("Costa Rica");
        countryNames.add("Côte d'Ivoire");
        countryNames.add("Croatia");
        countryNames.add("Cuba");
        countryNames.add("Cyprus");
        countryNames.add("Czech Republic");
        countryNames.add("Denmark");
        countryNames.add("Djibouti");
        countryNames.add("Dominica");
        countryNames.add("Dominican Republic");
        countryNames.add("Ecuador");
        countryNames.add("Egypt");
        countryNames.add("El Salvador");
        countryNames.add("Equatorial Guinea");
        countryNames.add("Eritrea");
        countryNames.add("Estonia");
        countryNames.add("Ethiopia");
        countryNames.add("Fiji");
        countryNames.add("Finland");
        countryNames.add("France");
        countryNames.add("Gabon");
        countryNames.add("Gambia");
        countryNames.add("Georgia");
        countryNames.add("Germany");
        countryNames.add("Ghana");
        countryNames.add("Greece");
        countryNames.add("Grenada");
        countryNames.add("Guatemala");
        countryNames.add("Guinea");
        countryNames.add("Guinea-Bissau");
        countryNames.add("Guyana");
        countryNames.add("Haiti");
        countryNames.add("Holy See (Vatican City State)");
        countryNames.add("Honduras");
        countryNames.add("Hungary");
        countryNames.add("Iceland");
        countryNames.add("India");
        countryNames.add("Indonesia");
        countryNames.add("Iran, Islamic Republic of");
        countryNames.add("Iraq");
        countryNames.add("Ireland");
        countryNames.add("Israel");
        countryNames.add("Italy");
        countryNames.add("Jamaica");
        countryNames.add("Japan");
        countryNames.add("Jordan");
        countryNames.add("Kazakhstan");
        countryNames.add("Kenya");
        countryNames.add("Kiribati");
        countryNames.add("Korea, Republic of");
        countryNames.add("Kuwait");
        countryNames.add("Kyrgyzstan");
        countryNames.add("Lao People's Democratic Republic");
        countryNames.add("Latvia");
        countryNames.add("Lebanon");
        countryNames.add("Lesotho");
        countryNames.add("Liberia");
        countryNames.add("Libya");
        countryNames.add("Liechtenstein");
        countryNames.add("Lithuania");
        countryNames.add("Luxembourg");
        countryNames.add("Macedonia, The Former Yugoslav Republic of");
        countryNames.add("Madagascar");
        countryNames.add("Malawi");
        countryNames.add("Malaysia");
        countryNames.add("Maldives");
        countryNames.add("Mali");
        countryNames.add("Malta");
        countryNames.add("Marshall Islands");
        countryNames.add("Mauritania");
        countryNames.add("Mauritius");
        countryNames.add("Mexico");
        countryNames.add("Micronesia, Federated States of");
        countryNames.add("Moldova, Republic of");
        countryNames.add("Monaco");
        countryNames.add("Mongolia");
        countryNames.add("Montenegro");
        countryNames.add("Morocco");
        countryNames.add("Mozambique");
        countryNames.add("Myanmar");
        countryNames.add("Namibia");
        countryNames.add("Nauru");
        countryNames.add("Nepal");
        countryNames.add("Netherlands");
        countryNames.add("New Zealand");
        countryNames.add("Nicaragua");
        countryNames.add("Niger");
        countryNames.add("Nigeria");
        countryNames.add("Norway");
        countryNames.add("Oman");
        countryNames.add("Pakistan");
        countryNames.add("Palau");
        countryNames.add("Palestine, State of");
        countryNames.add("Panama");
        countryNames.add("Papua New Guinea");
        countryNames.add("Paraguay");
        countryNames.add("Peru");
        countryNames.add("Philippines");
        countryNames.add("Poland");
        countryNames.add("Portugal");
        countryNames.add("Qatar");
        countryNames.add("Romania");
        countryNames.add("Russian Federation");
        countryNames.add("Rwanda");
        countryNames.add("Saint Kitts and Nevis");
        countryNames.add("Saint Lucia");
        countryNames.add("Saint Vincent and the Grenadines");
        countryNames.add("Samoa");
        countryNames.add("San Marino");
        countryNames.add("Sao Tome and Principe");
        countryNames.add("Saudi Arabia");
        countryNames.add("Senegal");
        countryNames.add("Serbia");
        countryNames.add("Seychelles");
        countryNames.add("Sierra Leone");
        countryNames.add("Singapore");
        countryNames.add("Slovakia");
        countryNames.add("Slovenia");
        countryNames.add("Solomon Islands");
        countryNames.add("Somalia");
        countryNames.add("South Africa");
        countryNames.add("South Sudan");
        countryNames.add("Spain");
        countryNames.add("Sri Lanka");
        countryNames.add("Sudan");
        countryNames.add("Suriname");
        countryNames.add("Swaziland");
        countryNames.add("Sweden");
        countryNames.add("Switzerland");
        countryNames.add("Syrian Arab Republic");
        countryNames.add("Taiwan, Province of China");
        countryNames.add("Tajikistan");
        countryNames.add("Tanzania, United Republic of");
        countryNames.add("Thailand");
        countryNames.add("Timor-Leste");
        countryNames.add("Togo");
        countryNames.add("Tonga");
        countryNames.add("Trinidad and Tobago");
        countryNames.add("Tunisia");
        countryNames.add("Turkey");
        countryNames.add("Turkmenistan");
        countryNames.add("Tuvalu");
        countryNames.add("Uganda");
        countryNames.add("Ukraine");
        countryNames.add("United Arab Emirates");
        countryNames.add("United Kingdom");
        countryNames.add("United States");
        countryNames.add("Uruguay");
        countryNames.add("Uzbekistan");
        countryNames.add("Vanuatu");
        countryNames.add("Venezuela, Bolivarian Republic of");
        countryNames.add("Viet Nam");
        countryNames.add("Western Sahara");
        countryNames.add("Yemen");
        countryNames.add("Zambia");
        countryNames.add("Zimbabwe");
    }

}
